Other data formats
-------------------

There are a lot of data formats out there. Rather than cover all of them, here are some common ones that you may come across

NetCDF
~~~~~~

Network Common Data Format. This is a binary file format which store large arrays of data that are linked in some ways. Often used for spatial data. Arrays will be latitude, longitude and then values based on those arrays, e.g. sea surface temperature. It can handle multiple dimensions, so it is possible to store three-dimensional field that vary in time (4D!). 
